trainset = read.table("/Users/FrancisLin/Desktop/Machine Learning/Project/train.csv", header = TRUE, sep = ",")

fullrow = rep(FALSE, nrow(trainset))
for(i in 1:nrow(trainset))
{
fullrow[i] = !any(is.na(trainset[i,29:147]))
}

print(fullrow)

varnames <-c(paste("Ret_", 2:120, sep=""))
fullform = as.formula(paste("Ret_PlusOne ~ ",paste(varnames,collapse="+")))

print(fullform)

lreg1 = lm(fullform, data = trainset, subset = fullrow)

summary(lreg1)


lreg2 = step(lreg1, direction = "both")
summary(lreg2)

# Plot of residuals versus fitted values
plot(as.numeric(lreg2$fit), as.numeric(lreg2$resid), pch = 1, xlab = "Fitted Values", ylab = "Residuals", cex.axis = 1.3, cex.lab = 1.3)

# Normal probability plot
qqnorm(as.numeric(lreg2$resid), cex.axis=1.3, cex.lab=1.3, pch=1, main="")
qqline(as.numeric(lreg2$resid))

# Plot of residuals versus time
plot(lreg2$resid, xlab = "Time", ylab = "Residuals", cex.axis = 1.3, cex.lab = 1.3, pch = 16, main = "Residual vs. Time Plot")


cookdistance = as.numeric(cooks.distance(lreg2))
sort(pf(cookdistance,91,22298),decreasing = TRUE)[1:5]

#------------Homework 3---------------------------#

# 1. 
RetsOnly = trainset[fullrow, 29:147]
pcaout = princomp(RetsOnly) 
summary(pcaout)

# 2.
tempframe <- trainset[fullrow, 29:147]
grep("Ret_PlusOne", colnames(trainset))
tempframe$Ret_PlusOne = trainset[fullrow, 208]
tempframe$comp1 = pcaout$scores[,1]

lreg3 = lm(formula = Ret_PlusOne ~ Ret_4 + Ret_5 + Ret_6 + Ret_7 + Ret_8 + 
    Ret_9 + Ret_10 + Ret_12 + Ret_13 + Ret_14 + Ret_15 + Ret_16 + 
    Ret_17 + Ret_18 + Ret_19 + Ret_20 + Ret_21 + Ret_22 + Ret_23 + 
    Ret_24 + Ret_25 + Ret_26 + Ret_27 + Ret_28 + Ret_29 + Ret_31 + 
    Ret_33 + Ret_34 + Ret_36 + Ret_37 + Ret_38 + Ret_40 + Ret_41 + 
    Ret_42 + Ret_43 + Ret_44 + Ret_48 + Ret_49 + Ret_50 + Ret_53 + 
    Ret_55 + Ret_57 + Ret_58 + Ret_59 + Ret_60 + Ret_61 + Ret_62 + 
    Ret_64 + Ret_65 + Ret_66 + Ret_68 + Ret_69 + Ret_70 + Ret_71 + 
    Ret_72 + Ret_73 + Ret_74 + Ret_75 + Ret_77 + Ret_78 + Ret_79 + 
    Ret_80 + Ret_81 + Ret_82 + Ret_83 + Ret_84 + Ret_85 + Ret_86 + 
    Ret_87 + Ret_89 + Ret_90 + Ret_91 + Ret_92 + Ret_95 + Ret_99 + 
    Ret_100 + Ret_101 + Ret_102 + Ret_103 + Ret_104 + Ret_105 + 
    Ret_107 + Ret_109 + Ret_113 + Ret_114 + Ret_115 + Ret_116 + 
    Ret_117 + Ret_119 + Ret_120 + comp1, data = tempframe)

AIC(lreg2)
AIC(lreg3)
extractAIC(lreg2)
extractAIC(lreg3)

# 3. 
# t1.
t1 = lm(formula = Ret_PlusOne ~ Ret_4*Ret_5 + Ret_6 + Ret_7 + Ret_8 + 
    Ret_9 + Ret_10 + Ret_12 + Ret_13 + Ret_14 + Ret_15 + Ret_16 + 
    Ret_17 + Ret_18 + Ret_19 + Ret_20 + Ret_21 + Ret_22 + Ret_23 + 
    Ret_24 + Ret_25 + Ret_26 + Ret_27 + Ret_28 + Ret_29 + Ret_31 + 
    Ret_33 + Ret_34 + Ret_36 + Ret_37 + Ret_38 + Ret_40 + Ret_41 + 
    Ret_42 + Ret_43 + Ret_44 + Ret_48 + Ret_49 + Ret_50 + Ret_53 + 
    Ret_55 + Ret_57 + Ret_58 + Ret_59 + Ret_60 + Ret_61 + Ret_62 + 
    Ret_64 + Ret_65 + Ret_66 + Ret_68 + Ret_69 + Ret_70 + Ret_71 + 
    Ret_72 + Ret_73 + Ret_74 + Ret_75 + Ret_77 + Ret_78 + Ret_79 + 
    Ret_80 + Ret_81 + Ret_82 + Ret_83 + Ret_84 + Ret_85 + Ret_86 + 
    Ret_87 + Ret_89 + Ret_90 + Ret_91 + Ret_92 + Ret_95 + Ret_99 + 
    Ret_100 + Ret_101 + Ret_102 + Ret_103 + Ret_104 + Ret_105 + 
    Ret_107 + Ret_109 + Ret_113 + Ret_114 + Ret_115 + Ret_116 + 
    Ret_117 + Ret_119 + Ret_120, data = tempframe)
    
AIC(t1)

# t2.
t2 = lm(formula = Ret_PlusOne ~ Ret_4*Ret_5*Ret_6 + Ret_7 + Ret_8 + 
    Ret_9 + Ret_10 + Ret_12 + Ret_13 + Ret_14 + Ret_15 + Ret_16 + 
    Ret_17 + Ret_18 + Ret_19 + Ret_20 + Ret_21 + Ret_22 + Ret_23 + 
    Ret_24 + Ret_25 + Ret_26 + Ret_27 + Ret_28 + Ret_29 + Ret_31 + 
    Ret_33 + Ret_34 + Ret_36 + Ret_37 + Ret_38 + Ret_40 + Ret_41 + 
    Ret_42 + Ret_43 + Ret_44 + Ret_48 + Ret_49 + Ret_50 + Ret_53 + 
    Ret_55 + Ret_57 + Ret_58 + Ret_59 + Ret_60 + Ret_61 + Ret_62 + 
    Ret_64 + Ret_65 + Ret_66 + Ret_68 + Ret_69 + Ret_70 + Ret_71 + 
    Ret_72 + Ret_73 + Ret_74 + Ret_75 + Ret_77 + Ret_78 + Ret_79 + 
    Ret_80 + Ret_81 + Ret_82 + Ret_83 + Ret_84 + Ret_85 + Ret_86 + 
    Ret_87 + Ret_89 + Ret_90 + Ret_91 + Ret_92 + Ret_95 + Ret_99 + 
    Ret_100 + Ret_101 + Ret_102 + Ret_103 + Ret_104 + Ret_105 + 
    Ret_107 + Ret_109 + Ret_113 + Ret_114 + Ret_115 + Ret_116 + 
    Ret_117 + Ret_119 + Ret_120, data = tempframe)
    
AIC(t2)

# t3.
t3 = lm(formula = Ret_PlusOne ~ Ret_4*Ret_5*Ret_6*Ret_7 + Ret_8 + 
    Ret_9 + Ret_10 + Ret_12 + Ret_13 + Ret_14 + Ret_15 + Ret_16 + 
    Ret_17 + Ret_18 + Ret_19 + Ret_20 + Ret_21 + Ret_22 + Ret_23 + 
    Ret_24 + Ret_25 + Ret_26 + Ret_27 + Ret_28 + Ret_29 + Ret_31 + 
    Ret_33 + Ret_34 + Ret_36 + Ret_37 + Ret_38 + Ret_40 + Ret_41 + 
    Ret_42 + Ret_43 + Ret_44 + Ret_48 + Ret_49 + Ret_50 + Ret_53 + 
    Ret_55 + Ret_57 + Ret_58 + Ret_59 + Ret_60 + Ret_61 + Ret_62 + 
    Ret_64 + Ret_65 + Ret_66 + Ret_68 + Ret_69 + Ret_70 + Ret_71 + 
    Ret_72 + Ret_73 + Ret_74 + Ret_75 + Ret_77 + Ret_78 + Ret_79 + 
    Ret_80 + Ret_81 + Ret_82 + Ret_83 + Ret_84 + Ret_85 + Ret_86 + 
    Ret_87 + Ret_89 + Ret_90 + Ret_91 + Ret_92 + Ret_95 + Ret_99 + 
    Ret_100 + Ret_101 + Ret_102 + Ret_103 + Ret_104 + Ret_105 + 
    Ret_107 + Ret_109 + Ret_113 + Ret_114 + Ret_115 + Ret_116 + 
    Ret_117 + Ret_119 + Ret_120, data = tempframe)
    
AIC(t3)

# t4.
t4 = lm(formula = Ret_PlusOne ~ Ret_4*Ret_5*Ret_6*Ret_7*Ret_8 + 
    Ret_9 + Ret_10 + Ret_12 + Ret_13 + Ret_14 + Ret_15 + Ret_16 + 
    Ret_17 + Ret_18 + Ret_19 + Ret_20 + Ret_21 + Ret_22 + Ret_23 + 
    Ret_24 + Ret_25 + Ret_26 + Ret_27 + Ret_28 + Ret_29 + Ret_31 + 
    Ret_33 + Ret_34 + Ret_36 + Ret_37 + Ret_38 + Ret_40 + Ret_41 + 
    Ret_42 + Ret_43 + Ret_44 + Ret_48 + Ret_49 + Ret_50 + Ret_53 + 
    Ret_55 + Ret_57 + Ret_58 + Ret_59 + Ret_60 + Ret_61 + Ret_62 + 
    Ret_64 + Ret_65 + Ret_66 + Ret_68 + Ret_69 + Ret_70 + Ret_71 + 
    Ret_72 + Ret_73 + Ret_74 + Ret_75 + Ret_77 + Ret_78 + Ret_79 + 
    Ret_80 + Ret_81 + Ret_82 + Ret_83 + Ret_84 + Ret_85 + Ret_86 + 
    Ret_87 + Ret_89 + Ret_90 + Ret_91 + Ret_92 + Ret_95 + Ret_99 + 
    Ret_100 + Ret_101 + Ret_102 + Ret_103 + Ret_104 + Ret_105 + 
    Ret_107 + Ret_109 + Ret_113 + Ret_114 + Ret_115 + Ret_116 + 
    Ret_117 + Ret_119 + Ret_120, data = tempframe)
    
AIC(t4)

# t5.
t5 = lm(formula = Ret_PlusOne ~ Ret_4*Ret_5*Ret_6*Ret_7*Ret_8*Ret_9 + 
    Ret_10 + Ret_12 + Ret_13 + Ret_14 + Ret_15 + Ret_16 + 
    Ret_17 + Ret_18 + Ret_19 + Ret_20 + Ret_21 + Ret_22 + Ret_23 + 
    Ret_24 + Ret_25 + Ret_26 + Ret_27 + Ret_28 + Ret_29 + Ret_31 + 
    Ret_33 + Ret_34 + Ret_36 + Ret_37 + Ret_38 + Ret_40 + Ret_41 + 
    Ret_42 + Ret_43 + Ret_44 + Ret_48 + Ret_49 + Ret_50 + Ret_53 + 
    Ret_55 + Ret_57 + Ret_58 + Ret_59 + Ret_60 + Ret_61 + Ret_62 + 
    Ret_64 + Ret_65 + Ret_66 + Ret_68 + Ret_69 + Ret_70 + Ret_71 + 
    Ret_72 + Ret_73 + Ret_74 + Ret_75 + Ret_77 + Ret_78 + Ret_79 + 
    Ret_80 + Ret_81 + Ret_82 + Ret_83 + Ret_84 + Ret_85 + Ret_86 + 
    Ret_87 + Ret_89 + Ret_90 + Ret_91 + Ret_92 + Ret_95 + Ret_99 + 
    Ret_100 + Ret_101 + Ret_102 + Ret_103 + Ret_104 + Ret_105 + 
    Ret_107 + Ret_109 + Ret_113 + Ret_114 + Ret_115 + Ret_116 + 
    Ret_117 + Ret_119 + Ret_120, data = tempframe)
    
AIC(t5)

# t6.
t6 = lm(formula = Ret_PlusOne ~ Ret_4*Ret_5*Ret_6*Ret_7*Ret_8*Ret_9*Ret_10 + 
    Ret_12 + Ret_13 + Ret_14 + Ret_15 + Ret_16 + 
    Ret_17 + Ret_18 + Ret_19 + Ret_20 + Ret_21 + Ret_22 + Ret_23 + 
    Ret_24 + Ret_25 + Ret_26 + Ret_27 + Ret_28 + Ret_29 + Ret_31 + 
    Ret_33 + Ret_34 + Ret_36 + Ret_37 + Ret_38 + Ret_40 + Ret_41 + 
    Ret_42 + Ret_43 + Ret_44 + Ret_48 + Ret_49 + Ret_50 + Ret_53 + 
    Ret_55 + Ret_57 + Ret_58 + Ret_59 + Ret_60 + Ret_61 + Ret_62 + 
    Ret_64 + Ret_65 + Ret_66 + Ret_68 + Ret_69 + Ret_70 + Ret_71 + 
    Ret_72 + Ret_73 + Ret_74 + Ret_75 + Ret_77 + Ret_78 + Ret_79 + 
    Ret_80 + Ret_81 + Ret_82 + Ret_83 + Ret_84 + Ret_85 + Ret_86 + 
    Ret_87 + Ret_89 + Ret_90 + Ret_91 + Ret_92 + Ret_95 + Ret_99 + 
    Ret_100 + Ret_101 + Ret_102 + Ret_103 + Ret_104 + Ret_105 + 
    Ret_107 + Ret_109 + Ret_113 + Ret_114 + Ret_115 + Ret_116 + 
    Ret_117 + Ret_119 + Ret_120, data = tempframe)
    
AIC(t6)

# t7.
t7 = lm(formula = Ret_PlusOne ~ Ret_4*Ret_5*Ret_6*Ret_7*Ret_8*Ret_9*Ret_10*Ret_12 + 
    Ret_13 + Ret_14 + Ret_15 + Ret_16 + 
    Ret_17 + Ret_18 + Ret_19 + Ret_20 + Ret_21 + Ret_22 + Ret_23 + 
    Ret_24 + Ret_25 + Ret_26 + Ret_27 + Ret_28 + Ret_29 + Ret_31 + 
    Ret_33 + Ret_34 + Ret_36 + Ret_37 + Ret_38 + Ret_40 + Ret_41 + 
    Ret_42 + Ret_43 + Ret_44 + Ret_48 + Ret_49 + Ret_50 + Ret_53 + 
    Ret_55 + Ret_57 + Ret_58 + Ret_59 + Ret_60 + Ret_61 + Ret_62 + 
    Ret_64 + Ret_65 + Ret_66 + Ret_68 + Ret_69 + Ret_70 + Ret_71 + 
    Ret_72 + Ret_73 + Ret_74 + Ret_75 + Ret_77 + Ret_78 + Ret_79 + 
    Ret_80 + Ret_81 + Ret_82 + Ret_83 + Ret_84 + Ret_85 + Ret_86 + 
    Ret_87 + Ret_89 + Ret_90 + Ret_91 + Ret_92 + Ret_95 + Ret_99 + 
    Ret_100 + Ret_101 + Ret_102 + Ret_103 + Ret_104 + Ret_105 + 
    Ret_107 + Ret_109 + Ret_113 + Ret_114 + Ret_115 + Ret_116 + 
    Ret_117 + Ret_119 + Ret_120, data = tempframe)
    
AIC(t7)

# t8.
t8 = lm(formula = Ret_PlusOne ~ Ret_4*Ret_5*Ret_6*Ret_7*Ret_8*Ret_9*Ret_10*Ret_12*Ret_13 +  Ret_14 + Ret_15 + Ret_16 + 
    Ret_17 + Ret_18 + Ret_19 + Ret_20 + Ret_21 + Ret_22 + Ret_23 + 
    Ret_24 + Ret_25 + Ret_26 + Ret_27 + Ret_28 + Ret_29 + Ret_31 + 
    Ret_33 + Ret_34 + Ret_36 + Ret_37 + Ret_38 + Ret_40 + Ret_41 + 
    Ret_42 + Ret_43 + Ret_44 + Ret_48 + Ret_49 + Ret_50 + Ret_53 + 
    Ret_55 + Ret_57 + Ret_58 + Ret_59 + Ret_60 + Ret_61 + Ret_62 + 
    Ret_64 + Ret_65 + Ret_66 + Ret_68 + Ret_69 + Ret_70 + Ret_71 + 
    Ret_72 + Ret_73 + Ret_74 + Ret_75 + Ret_77 + Ret_78 + Ret_79 + 
    Ret_80 + Ret_81 + Ret_82 + Ret_83 + Ret_84 + Ret_85 + Ret_86 + 
    Ret_87 + Ret_89 + Ret_90 + Ret_91 + Ret_92 + Ret_95 + Ret_99 + 
    Ret_100 + Ret_101 + Ret_102 + Ret_103 + Ret_104 + Ret_105 + 
    Ret_107 + Ret_109 + Ret_113 + Ret_114 + Ret_115 + Ret_116 + 
    Ret_117 + Ret_119 + Ret_120, data = tempframe)
    
AIC(t8)

# t9.
t9 = lm(formula = Ret_PlusOne ~ Ret_4*Ret_5*Ret_6*Ret_7*Ret_8*Ret_9*Ret_10*Ret_12*Ret_13*Ret_14
    + Ret_15 + Ret_16 + 
    Ret_17 + Ret_18 + Ret_19 + Ret_20 + Ret_21 + Ret_22 + Ret_23 + 
    Ret_24 + Ret_25 + Ret_26 + Ret_27 + Ret_28 + Ret_29 + Ret_31 + 
    Ret_33 + Ret_34 + Ret_36 + Ret_37 + Ret_38 + Ret_40 + Ret_41 + 
    Ret_42 + Ret_43 + Ret_44 + Ret_48 + Ret_49 + Ret_50 + Ret_53 + 
    Ret_55 + Ret_57 + Ret_58 + Ret_59 + Ret_60 + Ret_61 + Ret_62 + 
    Ret_64 + Ret_65 + Ret_66 + Ret_68 + Ret_69 + Ret_70 + Ret_71 + 
    Ret_72 + Ret_73 + Ret_74 + Ret_75 + Ret_77 + Ret_78 + Ret_79 + 
    Ret_80 + Ret_81 + Ret_82 + Ret_83 + Ret_84 + Ret_85 + Ret_86 + 
    Ret_87 + Ret_89 + Ret_90 + Ret_91 + Ret_92 + Ret_95 + Ret_99 + 
    Ret_100 + Ret_101 + Ret_102 + Ret_103 + Ret_104 + Ret_105 + 
    Ret_107 + Ret_109 + Ret_113 + Ret_114 + Ret_115 + Ret_116 + 
    Ret_117 + Ret_119 + Ret_120, data = tempframe)
    
AIC(t9)

# t10.
t10 = lm(formula = Ret_PlusOne ~ Ret_4*Ret_5*Ret_6*Ret_7*Ret_8*Ret_9*Ret_10*Ret_12*Ret_13*Ret_14*Ret_15 + Ret_16 + 
    Ret_17 + Ret_18 + Ret_19 + Ret_20 + Ret_21 + Ret_22 + Ret_23 + 
    Ret_24 + Ret_25 + Ret_26 + Ret_27 + Ret_28 + Ret_29 + Ret_31 + 
    Ret_33 + Ret_34 + Ret_36 + Ret_37 + Ret_38 + Ret_40 + Ret_41 + 
    Ret_42 + Ret_43 + Ret_44 + Ret_48 + Ret_49 + Ret_50 + Ret_53 + 
    Ret_55 + Ret_57 + Ret_58 + Ret_59 + Ret_60 + Ret_61 + Ret_62 + 
    Ret_64 + Ret_65 + Ret_66 + Ret_68 + Ret_69 + Ret_70 + Ret_71 + 
    Ret_72 + Ret_73 + Ret_74 + Ret_75 + Ret_77 + Ret_78 + Ret_79 + 
    Ret_80 + Ret_81 + Ret_82 + Ret_83 + Ret_84 + Ret_85 + Ret_86 + 
    Ret_87 + Ret_89 + Ret_90 + Ret_91 + Ret_92 + Ret_95 + Ret_99 + 
    Ret_100 + Ret_101 + Ret_102 + Ret_103 + Ret_104 + Ret_105 + 
    Ret_107 + Ret_109 + Ret_113 + Ret_114 + Ret_115 + Ret_116 + 
    Ret_117 + Ret_119 + Ret_120, data = tempframe)
    
AIC(t10)

# AIC Summaries
AIC(lreg2)
AIC(t1)
AIC(t2)
AIC(t3)
AIC(t4)
AIC(t5)
AIC(t6)
AIC(t7)
AIC(t8)
AIC(t9)
AIC(t10)